services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  Tourze\OAuth2ServerBundle\Controller\:
    resource: '../../Controller/'
  Tourze\OAuth2ServerBundle\DataFixtures\:
    resource: '../../DataFixtures/'
  Tourze\OAuth2ServerBundle\Repository\:
    resource: '../../Repository/'
  Tourze\OAuth2ServerBundle\Service\:
    resource: '../../Service/'
