services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    public: true

  Tourze\OAuth2ServerBundle\Controller\:
    resource: '../../Controller/'

  Tourze\OAuth2ServerBundle\Repository\:
    resource: '../../Repository/'
  Tourze\OAuth2ServerBundle\Service\:
    resource: '../../Service/'
  Tourze\OAuth2ServerBundle\DataFixtures\:
    resource: '../../DataFixtures/'
    tags: ['doctrine.fixture.orm']

  # Mock services for testing
  Tourze\EasyAdminMenuBundle\Service\LinkGeneratorInterface:
    class: Tourze\OAuth2ServerBundle\Tests\Mock\MockLinkGenerator
